apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-ds-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-100"
spec:
  project: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  destination:
    namespace: prod
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/max-pfeiffer/device-statistics.git
    path: kubernetes_deployment/helm-charts/ds-app
    targetRevision: "feature/consolidate-helm-charts"
    helm:
      valueFiles:
        - ../../helm-values/prod/ds-app.yaml
