apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: prod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-400"
spec:
  description: Production environment
  sourceRepos:
    - '*'
  destinations:
    - namespace: prod
      server: '*'