"""initial migration

Revision ID: 6ad3c1d5a511
Revises: 
Create Date: 2025-11-13 20:08:17.347023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6ad3c1d5a511'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('migrationmetadata',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('after_migration_revision', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('before_migration_revision', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rolled_back', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userdevicetype',
    sa.Column('user_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('device_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userdevicetype')
    op.drop_table('migrationmetadata')
    # ### end Alembic commands ###
