apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: database-migrations
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "90"
spec:
  project: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/max-pfeiffer/device-statistics.git
    path: kubernetes_deployment/helm-charts/ds-job
    targetRevision: "main"
    helm:
      valueFiles:
        - ../../helm-values/dev/job-database-migrations.yaml
