apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-200"
spec:
  project: dev
  syncPolicy:
    automated: {}
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  source:
    chart: postgresql
    repoURL: "oci://registry-1.docker.io/bitnamicharts/postgresql"
    targetRevision: "18.1.4"
    helm:
      valuesObject:
        architecture: "standalone"
        auth:
          existingSecret: "postgresql"
          database: "devicestatistics"
          username: "testuser"
        primary:
          persistence:
            size: 200M
