apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  description: Development environment
  sourceRepos:
    - '*'
  destinations:
    - namespace: dev
      server: '*'